# Generated by Django 4.2.5 on 2023-11-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('site', models.CharField(max_length=100)),
                ('coleta', models.BooleanField()),
                ('descarte', models.BooleanField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.regiao')),
            ],
        ),
    ]
