# Generated by Django 4.2.5 on 2023-11-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_empresa_cep_alter_empresa_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa')),
            ],
        ),
    ]
