# Generated by Django 4.2.5 on 2023-11-17 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0003_agendamentodescarte_agendamentocoleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentocoleta',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='agendamentodescarte',
            name='hora',
        ),
        migrations.AddField(
            model_name='agendamentocoleta',
            name='local',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço da Coleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentocoleta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentodescarte',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentocoleta',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendamentodescarte',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
